#!/bin/sh

SM_PARSER=../smparser
if [ ! -x $SM_PARSER ]; then echo "ERROR: $SM_PARSER not found Build it first."
fi
REF=$srcdir/T_smparser1.ref
IN=$srcdir/T_smparser1.in
OUT=T_smparser1.out

$SM_PARSER $IN a > $OUT
$SM_PARSER $IN a 1 >> $OUT
$SM_PARSER $IN a 2 >> $OUT
$SM_PARSER $IN a 3 >> $OUT
$SM_PARSER $IN a 4 >> $OUT
$SM_PARSER $IN a 5 >> $OUT

$SM_PARSER $IN "a b c" >> $OUT
$SM_PARSER $IN "a b c" 2 >> $OUT
$SM_PARSER $IN "a b c" 3 >> $OUT
$SM_PARSER $IN "a b c" 4 >> $OUT

$SM_PARSER $IN zzz >> $OUT
$SM_PARSER $IN zzz 1 >> $OUT
$SM_PARSER $IN zzz 2 >> $OUT

$SM_PARSER $IN hello >> $OUT
$SM_PARSER $IN hello 2 >> $OUT

cat $IN | $SM_PARSER - zzz >> $OUT
cat $IN | $SM_PARSER - "a b c" 2 >> $OUT


diff $REF $OUT 
